{{- if eq .Values.node_env "production" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}-certs
  namespace: simple-app
spec:
  dnsNames:
    - {{ .Values.domain }}
  issuerRef:
    name: {{ .Chart.Name }}-letsencrypt
    kind: Issuer
  secretName: {{ .Chart.Name }}-certs
{{- end }}