{{- if eq .Values.node_env "production" }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Chart.Name }}-letsencrypt
  namespace: simple-app
spec:
  acme:
    privateKeySecretRef:
      name: {{ .Chart.Name }}-letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: contour
{{- end }}